version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./my_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  worker:
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    build:
      context: './backend'
      dockerfile: Dockerfile
    depends_on:
      - db