version: '3'
services:
  web:
    depends_on:
      - db
      - worker
    ports:
     - '5000:5000'
      # host:container
    build:
      context: './app'
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./my_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    build:
      context: './db'
      dockerfile: Dockerfile

  worker:
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    build:
      context: './worker'
      dockerfile: Dockerfile
    depends_on:
      - db
